# Generated by Django 3.2.5 on 2022-04-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
