# Generated by Django 3.2.5 on 2022-05-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_auto_20220507_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetenceGroup',
            new_name='Bundle',
        ),
    ]
