# Generated by Django 3.2.5 on 2022-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0005_auto_20220507_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='bundles',
            field=models.ManyToManyField(related_name='competences', to='competence.Bundle'),
        ),
    ]
