# Generated by Django 3.2.5 on 2022-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
